VAR_TOPIC_MAPPING = {
    "c1010": "Inflation",
    "c1020": "Inflation",
    "c1110": "Inflation",
    "c1120": "Inflation",
    "c1150": "Inflation",
    "c1210": "Inflation",
    "c1220": "Inflation",
    "c2110": "Housing and credit access",
    "c2120": "Housing and credit access",
    "c3210": "Income and consumption",
    "c3220": "Income and consumption",
    "c4010": "Labour and economic growth",
    "c4020": "Labour and economic growth",
    "c4030": "Labour and economic growth",
    "c4031": "Labour and economic growth",
    "c5111": "Housing and credit access",
    "c6010": "Income and consumption",
    "c6020": "Income and consumption",
    "c6110": "Income and consumption",
    "c6120": "Income and consumption",
    "c7110": "Housing and credit access",
    "c7120": "Housing and credit access",
    "e2010": "Inflation",
    "e2020": "Inflation",
    "q2300": "Labour and economic growth",
    "q2350": "Labour and economic growth",
    "q2390": "Labour and economic growth",
    "q4010": "Housing and credit access",
}

VAR_LABEL_MAPPING = {
    "c1010": "Inflation perceptions over the previous 12 months (qualitative)",
    "c1020": "Inflation perceptions over the previous 12 months (% change)",
    "c1110": "Inflation expectations over the next 12 months (qualitative)",
    "c1120": "Inflation expectations over the next 12 months (% change)",
    "c1150": "Inflation expectations/uncertainty 12 months ahead (probabilistic bins)",
    "c1210": "Inflation expectations 3 years ahead (qualitative)",
    "c1220": "Inflation expectations 3 years ahead (% change)",
    "c2110": "Home price expectations 12 months ahead (qualitative)",
    "c2120": "Home price expectations 12 months ahead (% change)",
    "c3210": "Household income expectations 12 months ahead (qualitative)",
    "c3220": "Household income expectations 12 months ahead (% change)",
    "c4010": "Economic growth expectations for the next 12 months (qualitative)",
    "c4020": "Economic growth expectations for the next 12 months (% change)",
    "c4030": "Perceptions of the current unemployment rate (%)",
    "c4031": "Expected unemployment rate in the next 12 months (%)",
    "c5111": "Mortgage interest rate expectations 12 months ahead (%)",
    "c6010": "Household spending perceptions over the previous 12 months (qualitative)",
    "c6020": "Household spending perceptions over the previous 12 months (% change)",
    "c6110": "Household spending expectations over the next 12 months (qualitative)",
    "c6120": "Household spending expectations over the next 12 months (% change)",
    "c7110": "Perceived ease of credit access over the previous 12 months (qualitative)",
    "c7120": "Expected ease of credit access over the next 12 months (qualitative)",
    "e2010": "Inflation expectations 5 years ahead (qualitative)",
    "e2020": "Inflation expectations 5 years ahead (% change)",
    "q2300": "Probability of finding a job in the next 3 months (%)",
    "q2350": "Probability of losing one's job in the next 3 months (%)",
    "q2390": "Probability of looking for a job in the next 3 months (%)",
    "q4010": "Applied for credit over the previous 3 months (%)",
}


MAPPING_COLUMN_NAMES = {
    "Up": "up",
    "Down": "down",
    "The_same": "same",
    "Grow": "grow",  # c4010
    "Harder": "harder",  # c7110, c7120
    "Shrink": "shrink",  # c4010
    "Easier": "easier",  # c7110, c7120
    "Net_perc": "netdiff",
    "Mean": "mean_w",
    "Median": "median",
    "Yes": "yes",
    "Expectations_med": "expectations_med",
    "Uncertainty_med": "uncertainty_med",
    "Expectations_p25": "expectations_p25",
    "Expectations_p75": "expectations_p75",
    "Not_applicable": "notapplicable",
    "flag_N": "flag_n",
    "Var": "variable",
    "N": "sample_size",
    "N_Weighted": "population_size",
}

MAPPING_BREAKDOWN_AGE_VALUES = {
    "18-34 years": "1",
    "35-54 years": "2",
    "55-70 years": "3",
    "70+ years": "4",
}

COLUMNS_ORDER_DFS = [
    "date",
    "wave",
    "country",
    "breakdown_other",
    "breakdown_other_categ",
    "var_type",
    "variable",
    "qualitative_measure",
    "indicator",
    "value",
    "sd",
    "lb_95",
    "ub_95",
    "sample_size",
    "population_size",
    "fd_value",
    "fd_sd",
    "fd_lb_95",
    "fd_up_95",
    "fd_p_value",
]

COLUMNS_ORDER_DFE = [
    "date",
    "wave",
    "Topic",
    "Var_label",
    "Var",
    "Breakdown",
    "Breakdown_label",
    "N",
    "N_Weighted",
    "Mean",
    "Median",
    "Expectations_med",
    "Uncertainty_med",
    "Expectations_p25",
    "Expectations_p75",
    "The_same",
    "Up",
    "Down",
    "Net_perc",
    "Grow",
    "Shrink",
    "Not_applicable",
    "Harder",
    "Easier",
    "Yes",
    "flag_N",
]
